[project]
name = "raylib-imgui"
version = "0.1.0"
description = "A minimal example of how to use raylib with imgui-bundle"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["raylib==5.5.0.2", "imgui-bundle==1.6.1", "moderngl==5.12.0"]
